config/routes.rb
Rails.application.routes.draw do
  
    root 'pastries#index'

    resources :pastries do
    	resources :orders, only: [:new, :create, :show]
    end

    resources :users, except: [:show, :index] do
    	resources :pastries, only: [:index]
    end

    resources :orders, only: :show

    #This is a custom route to save having to use the users part of it (since you have to be logged in to do this)

    resource :session
	end

#Means that you need to go to/users/1/pastries/3 (i.e. creating a new pastry is within the user)
# User info lives in a session, so we don't actually need to go via a user to get to the pastries. We can just use the current session
#nested resources - probably want to look up

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	belongs_to :pastry

	validates :stripe_token, presence: true
end

app/models/pastry.rb
class Pastry < ActiveRecord::Base
	belongs_to :user
	has_many :orders

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  	#taken from paperclip github page

	validates :name, presence: true, uniqueness: true
	validates :price_in_pence, numericality: {greater_than: 50}
end

#changed avatar to image (as tyhat is what we're going to be using in the migration)

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :pastries
	has_many :orders

	validates :email, presence: true, uniqueness: true
	validates :username, presence: true, uniqueness:true

	def owns(pastry)
		
		pastry.user == self
			
		
		#check if owner of pastry
		#return true if true

	# can't access the session within the model so can't do pastry.user_id == session.user_id
		
	end

end

#references the Bcrypt gem to encrypt the password

#have to have password_digest in the model (i.e. in the database table)
#have to have password and password_corfirmation in whitelisted params (user_params)

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

#helper methods mean that they are available in ALL views
	helper_method :logged_in?, :current_user

	def logged_in?
		session[:user_id].present?
		#checking if there is a user_id present?
	end

	def current_user
		User.find(session[:user_id])
	end

	def require_user
		unless logged_in?
			flash[:error] = "You must be logged in to do that"
			redirect_to new_session_path
		end		
	end

	def require_owner
		
		unless current_user.owns(@pastry)
	        flash[:error] = "You must be the baker of the pastry to edit it"
	        redirect_to root_path
	    end
  	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController



	def new
	  	@pastry = Pastry.find(params[:pastry_id])
	  	@order = @pastry.orders.new
	end

	def create
		@pastry = Pastry.find(params[:pastry_id])
		@order = @pastry.orders.new(order_params)
		@order.user = current_user

			if @order.save
	     	flash[:success] = "Thanks for ordering!"
	     	logger.debug @order

	     	#logger helps with debugging, adds everything to the development.log file. Not the greatest resource
	    	redirect_to order_path(@order)

	    	# should be redirecting to the 'show' page (or action in this case)
	    	# Try to charge card here

	    	Stripe.api_key = Rails.application.secrets.stripe_secret_key

	    	Stripe::Charge.create(
	    		:amount => @pastry.price_in_pence,
	    		:currency => "gbp",
	    		:source => @order.stripe_token, #obtained with stripe.js
	    		:description => "Charge for #{@order.user.email}")
	    	

	    	# Copy the Stripe.api_key = part but after moving the api key into the secrets folder, will then need to reference that instead 
	    	# copy the key into config/secrets

	    	else
	     	flash[:error] = "Oops, that didn't work (order/payment)"
	     	render :new
	     	end
	end	



  
	def show
	end

private

	def order_params
		params.require(:order).permit(:stripe_token)
	end



end

app/controllers/pastries_controller.rb
class PastriesController < ApplicationController

  before_action :find_pastry, except: [:index, :destroy, :create, :new]
  before_action :require_user, except: [:index, :show]
  before_action :require_owner, only: [:edit, :update, :destroy]

  def index
  	@pastries = Pastry.all
  end
  	 
# hash can be written using the hash rocket or colon 

  def show
  	#@pastry = Pastry.find(params[:id])
  end

  def new
    @pastry = Pastry.new
  end

  def create

    @pastry = current_user.pastries.new(pastry_params)
    if @pastry.save
      flash[:success] = "Pastry added!"
      redirect_to root_path
    else
      flash[:error] = "Oops, something went wrong, please try again"
      render :new
    end
  end

#can render any of the views from the Pastry controller just by doing this


  def edit
    #@pastry = Pastry.find(params[:id])
    #require_owner      
  end

  def update
    #@pastry = Pastry.find(params[:id])
      if @pastry.update(pastry_params)
        flash[:success] = "Pastry updated!"
        redirect_to pastry_path(@pastry)
      else
        flash[:error] = "Oops, that didn't save, please try again"
        render :edit
      end
  end

  def destroy
    pastry = Pastry.find(params[:id])
    pastry.destroy 
    flash[:success] = "You have deleted your #{pastry.name}"
    redirect_to root_path
  end
  # Also not an instance variable because it isn't being passed through to a view
  # The reason its not an instance variable is that, if there were a view, that variable no longer exists! (i.e. it has just been deleted so what are they going to call)
 
  private

  def pastry_params
    params.require(:pastry).permit(:name, :price_in_pence, :description, :image)
  end
# Need to 'whitelist' the params - i.e. allow ONLY the params from the params hash (created from the http request) to be passed into the create method 

def find_pastry
  @pastry = Pastry.find(params[:id])
end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

	def create
	  	username = params[:session] [:username]
	  	password = params[:session] [:password]
	  	# :session comes from the name of the form!
	  	# digging into the nested hash (session is one key and username is the other)
	  	#not instance variables as we don't want them going to the view!
	  	@user = User.find_by(username: username)
	  	#look inside the username column for a user name that matches @username
	  	# .authenticate method comes from bcrypt
	  	if @user.present? and @user.authenticate(password)
	  		flash[:success] = "Logged in!"
	  		session[:user_id] = @user.id
	  		redirect_to root_path
	  	else
	  		flash[:error] = "Something went wrong"
	  		render :new
	  	end
	end

    def show

    end

    def destroy
    	reset_session
    	flash[:success] = "Logged out"
    	redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
	  	@user = User.new(user_params)
	  	
	  	if @user.save
	  		#log them in here
	  		#security thing, reset the session before starting another one. Reset_session also just comes with Rails
	  		reset_session
	  		session[:user_id] = @user.id
	  		#session is a keyword given to us by rails - behaves like a hash
	  		# user_id is a key within the session hash
			flash[:success] = "You have created a new user"
			redirect_to root_path
		else
			flash[:error] = "Something went wrong"
			render :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:success] = "You have updated your details"
			redirect_to root_path
		else
			flash[:error] = "Something went wrong"
			render :edit
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:success] = "User destroyed"
		redirect_to root_path
	end

private
	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation, :username)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pastries_helper.rb
module PastriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Breakfastr</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
		<script type="text/javascript">
		 var ready = function() {
		 	// This identifies your website in the createToken call below - NEED YOUR OWN TOKEN NOT THE ONE THAT COMES WITH THE SITE! login to do this
			Stripe.setPublishableKey($('body').data('stripe'));
			// Rails.application etc is now pointing to the file we added into the secrets file
			jQuery(function($) {
			  $('#new_order').submit(function(event) {
			    var $form = $(this);
			    // change to new_order. When I hit the 'submit' button on the new_order page, then do the rest of the code
			    // Disable the submit button to prevent repeated clicks
			    $form.find('button').prop('disabled', true);

			    Stripe.card.createToken($form, stripeResponseHandler);

			    // Prevent the form from submitting with the default action
			    return false;
			  });
			});
			function stripeResponseHandler(status, response) {
			  var $form = $('#new_order');
			  // again, need to put in new_order so that when the form is ??
			  if (response.error) {
			    // Show the errors on the form
			    $form.find('.payment-errors').text(response.error.message);
			    $form.find('button').prop('disabled', false);
			  } else {
			    // response contains id and card, which contains additional card details
			    var token = response.id;
			    // Insert the token into the form so it gets submitted to the server
			    $form.append($('<input type="hidden" name="order[stripe_token]" />').val(token));
			    // and submit
			    // also change to "order[stripe_token]" as that is the name
			    $form.get(0).submit();
			  }
			};
				// ...
		};

				$(document).ready(ready);
				$(document).on("page:load", ready);
		</script>
	</head>
	
	<body data-stripe="<%= Rails.application.secrets.stripe_public_key %>">
		<header>
			<%= link_to "Home", root_path %>
				<% if logged_in? %>
					<%= link_to "Add a pastry", new_pastry_path %>
					<%= link_to "Log out", session_path, method: :delete %>
				<% else %>
					<%= link_to "Log in", new_session_path %>
					<%= link_to "Sign Up", new_user_path %>
				<% end %>
		</header>

		<% flash.each do |k, v|%>
			<div class="flash <%= k %>">
			<p><%= v %></p>
		<% end %>


		<%= yield %>

	</body>
</html>

app/views/orders/new.html.erb
<h1>Pay for your <%= @pastry.name %> below</h1>

<%= simple_form_for [@pastry, @order], url: pastry_orders_path(@pastry) do |f| %>
<!-- stripe static form below -->

<span class="payment-errors"></span>

  <div class="form-row">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" data-stripe="number"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>CVC</span>
      <input type="text" size="4" data-stripe="cvc"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>Expiration (MM/YYYY)</span>
      <input type="text" size="2" data-stripe="exp-month"/>
    </label>
    <span> / </span>
    <input type="text" size="4" data-stripe="exp-year"/>
  </div>

  <button type="submit">Submit Payment</button>

<% end %>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/pastries/edit.html.erb
<h1>Editing <%= @pastry.name %></h1>

<%= simple_form_for @pastry do |f| %>
	 <%= f.input :name %>
	 <%= f.input :price_in_pence %>
	 <%= f.input :description %>
	 <%= f.button :submit %>
<% end %>

app/views/pastries/index.html.erb
<h1>All the Pastries!</h1>

<section class="pastries">
	<% @pastries.each do |pastry| %>
		<div class="pastry">
			<%= image_tag pastry.image.url(:thumb) %>
			<p>Name: <%= link_to pastry[:name], pastry_path(pastry) %></p>

			<p>Price: <%= number_to_currency(pastry.price_in_pence.to_f / 100, unit: "£")%>
				Description: <%= pastry[:description] %>
			    Added by: <%= pastry.user.username %>, User id: <%= pastry.user_id %></p>
		</div>
	<% end %>
</section>

app/views/pastries/new.html.erb
<h1>Add a new pastry</h1>

<%= simple_form_for @pastry do |f| %>
	 <%= f.input :name %>
	 <%= f.input :price_in_pence %>
	 <%= f.input :description %>
	 <%= f.input :image %>
	 
	 <%= f.button :submit %>
<% end %>

<!-- Need to add in the url as it defaults to /pastries instead of user_pastries_path, now taken out -->
<!--In order to create new one, you have to have a user! New patries HAVE to have a user-->

app/views/pastries/show.html.erb
<section class="pastry">
	<h1>Showing the <%= @pastry.name %></h1>

	<p> Name: <%= @pastry.name %></p>
	<p> Price: <%= link_to number_to_currency(@pastry.price_in_pence.to_f / 100, unit: "£"), new_pastry_order_path(@pastry) %></p>
	<p> Description: <%= @pastry.description %></p>
	<p> Added by: <%= @pastry.user.username %></p>

	<% if logged_in? and current_user.owns(@pastry) %>
		<div class="actions">
			<%= link_to "Edit Pastry", edit_pastry_path(@pastry) %>
			<%= link_to "Remove Pastry", pastry_path(@pastry), method: :delete %>
		</div>
	<% end %>
<section>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up!</h1>


<%= simple_form_for @user do |f| %>
	 <%= f.input :username %>
	 <%= f.input :email %>
	 <%= f.input :password %>
	 <%= f.input :password_confirmation %>
	 <%= f.button :submit %>
<% end %>

<!-- Simple_form KNOWS that username and password are required fields and therefore puts an asterisk before them -->